# Generated by Django 3.1.3 on 2020-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0004_institution_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='picked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
