# Generated by Django 3.1.3 on 2020-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0005_donation_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_time_picked',
            field=models.DateTimeField(null=True),
        ),
    ]
